globalVariables(
  names = c(
    ".parsnip_engine",
    ".",
    ".model_id",
    "fitted_wflw",
    "model_spec",
    "pred_wflw",
    "wflw",
    ".model_spec",
    "role",
    "variable",
    ".data_category",
    ".data_type",
    ".model_type",
    ".parsnip_fns",
    ".pred",
    ".resid",
    ".value",
    "actual",
    "predicted","rec_obj","value","name","x","training","testing"
    )
)
